const imgs = {
  arrow: "http://medoncall.co/static/media/ForwardArrow.2ede6e71.svg",
  redring: "http://medoncall.co/static/media/Rectangle%2013.cc916e6c.svg",
  apple: "http://medoncall.co/static/media/Applestore.56c2e69e.svg",
  gplay: "http://medoncall.co/static/media/googleplay.59320bb7.svg",
  drugc: "	http://medoncall.co/static/media/Condrugs.f1db0333.svg",
  pill: "http://medoncall.co/static/media/drugs.62a7744d.svg",
  arrowCurve: "	http://medoncall.co/static/media/Vector13.851a0cc9.svg",
  elipse: "http://medoncall.co/static/media/Ellipse%203.b291dd41.svg",
  phoneA: "http://medoncall.co/static/media/Rectangle1.320067d1.png",
  phoneB: "	http://medoncall.co/static/media/Rectangle2.6c76acc2.png",
  phoneC: "http://medoncall.co/static/media/consultation2.720aaf54.png",
  orangeCard: "http://medoncall.co/static/media/Rectangle%202.d979f6d4.svg",
  dottedA: "http://medoncall.co/static/media/line_one.6e1ec428.svg",
  dottedB: "http://medoncall.co/static/media/line_two.99c64c88.svg",
  dottedC: "http://medoncall.co/static/media/Vector8.aefc3665.svg",
  dottedD: "http://medoncall.co/static/media/Vector9.3be08267.svg",
  caret: "http://medoncall.co/static/media/Vector.b1086b3b.svg",
  right: "http://medoncall.co/static/media/Vector10.76db3e72.svg",
  left: "http://medoncall.co/static/media/Vector11.d644a8c6.svg",
  trape: "	http://medoncall.co/static/media/Rectangle5.9bc10eb4.svg",
  red: "http://medoncall.co/static/media/Rectangle18.267b380a.svg",
  black: "	http://medoncall.co/static/media/Rectangle19.1b4c3a9b.svg",
  red2: "http://medoncall.co/static/media/Rectangle20.c1c0ad2b.svg",
  blue: "http://medoncall.co/static/media/Rectangle21.2919e792.svg",
  rec2: "http://medoncall.co/static/media/Rectangle15.a17190ab.svg",
};

export default imgs;
